### ISSUE TITLE
Input "version" is never used, when Flutter already installed

### ISSUE THREAD

**Issue by richard-bogdan-bitrise** [DroidsOnRoids/bitrise-step-flutter#12]
If Flutter already installed, then it won't check the input version, and wrong version of Flutter will be used.

Please see related code:
[A](https://github.com/DroidsOnRoids/bitrise-step-flutter/blob/0.0.7/main.go#L35)
[B](https://github.com/DroidsOnRoids/bitrise-step-flutter/blob/0.0.7/platformutil.go#L10)
[C](https://github.com/DroidsOnRoids/bitrise-step-flutter/blob/0.0.7/main.go#L47)

I think it should check the version too, or at least add a warning message that in this case the version will be ignored (and make the input not required).

**Comment by koral--** [comment]
Thanks for pointing this out.

At the time of creating this step there was no preinstalled Flutter on Bitrise stack, so I've never considered case when Flutter is installed.
