### ISSUE TITLE
--no-build option is not recognized

### ISSUE THREAD

**Issue by ncuillery** [DroidsOnRoids/bitrise-step-flutter#16]
I tried to launch my integration tests using this step `drive --driver=test_driver/app_test.dart --no-build` but I got:

```
Executing Flutter command: drive --driver=test_driver/app_test.dart --no-build
Could not find an option named "build".
```

When using a custom script step with the same command `flutter drive --driver=test_driver/app_test.dart --no-build` it works.

**Comment by koral--** [comment]
Are you sure that Flutter version specified in step input supports [no]-build option?
If so could you share bitrise.yml which reproduces this issue?

**Comment by ncuillery** [comment]
Indeed I didn't notice that the step was downloading its own Flutter SDK (0.9.4 by default...).
