### ISSUE TITLE
 Could not extract Flutter SDK, error: exit status 128

### ISSUE THREAD

**Issue by wklimczyk** [DroidsOnRoids/bitrise-step-flutter#17]
We've set Flutter version to TAG 1.17.0
Flutter install when setting stable version to: 1.17.0
success

then 
Flutter command with version set to: 1.17.0
pub get
Extracting Flutter SDK to /Users/vagrant/Library/flutter
Version 1.17.0 not found in releases, trying snapshot.
Could not extract Flutter SDK, error: exit status 128
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter@0 (exit code: 2)                       

The version exists 
https://github.com/flutter/flutter/releases/tag/1.17.0
also here: https://flutter.dev/docs/development/tools/sdk/releases
also it's installed via Flutter install

**Comment by mateusfsilva** [comment]
Same with version 1.17.3

```
Extracting Flutter SDK to /opt/flutter
Version 1.17.3 not found in releases, trying snapshot.
Could not extract Flutter SDK, error: exit status 128
```

I think that is because of the name change from version 1.17.0 which does not has the v before the version number.

**Comment by koral--** [comment]
Thanks @mateusfsilva!
Indeed, it seems that Google have removed `v` prefix starting from version `1.17.x`.

**Comment by koral--** [comment]
Fixed in 0.0.10 https://github.com/bitrise-io/bitrise-steplib/pull/2571

**Comment by lukaszdebowski** [comment]
@koral-- Just FYI, I've had this issue where the Bitrise step could not be updated from version 0.0.9 to 0.0.10 using the "red arrow" button that usually updates the step to the latest version - it says that the latest is 0.0.9.

But if you add the step as a brand new step, then the version says it is 0.0.10 (even tho the "latest step version" still says 0.0.9). 

Might wanna look into that, thanks for the update anyway 👍

**Comment by koral--** [comment]
@lukaszdebowski it seems to be related to this change: https://blog.bitrise.io/new-options-for-locking-step-versions
