### ISSUE TITLE
sligtht change for when running android build

### ISSUE THREAD

**Issue by gedw99** [DroidsOnRoids/bitrise-step-flutter#2]
Basically you need to accept a license.
Its because your running a slightly older android setup.

x-MacBook-Pro:ci apple$ flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
/Users/apple/Library/Android/sdk/tools/bin/sdkmanager --update

**Comment by koral--** [comment]
Which bitrise stack you are using?

**Comment by gedw99** [comment]
Hybrid stack, with both Android tools and Xcode 8

locally i get new issues because i am on JDK java 10.0.1
then do flutter doctor and it will ask you to do the licesne review and its plain sailing after that

**Comment by gedw99** [comment]
i did the "Enabling Bitrise Support user for this app, wait a sec..."
you have access now i guess ?

https://www.bitrise.io/app/e510324ebb5151ff#/builds

**Comment by koral--** [comment]
OK, I was able to reproduce that and I'll fix it ASAP.
PS I'm not a bitrise employee.

**Comment by koral--** [comment]
Fixed in version 0.0.2 thanks for the report.
