### ISSUE TITLE
Failing to install junitreport

### ISSUE THREAD

**Issue by sommestad** [DroidsOnRoids/bitrise-step-flutter#26]
Getting the below issue in 0.1.3 version of the step. Have tried re-running multiple times.

> Failed to install Step dependency, error: command failed with exit status 100 (sudo "apt-get" "update"): Hit:1 https://packages.cloud.google.com/apt cloud-sdk InRelease
> Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
> Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
> Hit:4 https://deb.nodesource.com/node_16.x focal InRelease
> Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> Hit:6 http://archive.ubuntu.com/ubuntu focal InRelease
> Hit:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Hit:10 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
> Err:5 https://dl.yarnpkg.com/debian stable InRelease
>   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> Hit:11 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease
> Hit:9 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
> Reading package lists...
> W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
> E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed. (exit code: 1)

**Comment by koral--** [comment]
Sorry for the late reply. I missed the notification.
It's not an issue of this step but of the system you are running it.

If anyone has the same issue in the future, the solution is to invoke the following shell command before the step:
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`
