### ISSUE TITLE
Version master not found in releases, trying snapshot.

### ISSUE THREAD

**Issue by AnthonyDadeWT** [DroidsOnRoids/bitrise-step-flutter#28]
I noticed this step is having issues fetching specific Flutter versions I am requesting it use when executing a command. I get the error:

When following the example posted in the screenshot, I get an error.

Extracting Flutter SDK to /Users/vagrant/Library/flutter
Version 13.13.9-stable not found in releases, trying snapshot.
Could not extract Flutter SDK, error: exit status 128

![Screenshot 2023-12-22 at 9 44 30 AM](https://github.com/DroidsOnRoids/bitrise-step-flutter/assets/145477058/0f66e2e5-cfd4-47f0-978e-9b9145d93cad)

Using "master" I get a similar error but the command does not terminate, however because the "snapshot" version is an older version of Flutter, I am not able to use --flavor in my test command because it was later implemented in a later version.

Extracting Flutter SDK to /Users/vagrant/Library/flutter
Version master not found in releases, trying snapshot.
Executing Flutter command: test integration_test/login_test.dart --flavor dev

**Comment by koral--** [comment]
Is there maybe something like:
```
Flutter SDK directory already exists, skipping installation.
Already installed Flutter version 3.3.10 will be used instead of requested version master 
```
in your build logs?

**Comment by AnthonyDadeWT** [comment]
No I don't this happens both when I use the Flutter install step at the start of my workflow, and without it.

**Comment by koral--** [comment]
Please share a minimal sample project which reproduces this issue, along with bitrise.yml included.

**Comment by koral--** [comment]
Fixed in https://github.com/DroidsOnRoids/bitrise-step-flutter/pull/32
