### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by paulunder** [DroidsOnRoids/bitrise-step-flutter#30]
Hi guys I suddenly get this error:

`error: externally-managed-environment`

This came up during the workflow step of
`packages pub run build_runner build --delete-conflicting-outputs`

and I cannot see why it is - can you help me here?

This is the whole message:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'six'
six Python module not found, installing it
WARNING: The directory '/Users/vagrant/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.

If you wish to install a Python library that isn't in Homebrew,
use a virtual environment:

python3 -m venv path/to/venv
source path/to/venv/bin/activate
python3 -m pip install xyz

If you wish to install a Python application that isn't in Homebrew,
it may be easiest to use 'pipx install xyz', which will manage a
virtual environment for you. You can install pipx with

brew install pipx

You may restore the old behavior of pip by passing
the '--break-system-packages' flag to pip, or by adding
'break-system-packages = true' to your pip.conf file. The latter
will permanently disable this error.

If you disable this error, we STRONGLY recommend that you additionally
pass the '--user' flag to pip, or set 'user = true' in your pip.conf
file. Failure to do this can result in a broken Homebrew installation.

Read more about this behavior here: <https://peps.python.org/pep-0668/>;
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Could not setup macOS environment, error: exit status 1
```

I reached out to bitrise support and they said - thanks for replying

the said that:

_The error message explained that the curl command failed because the environment is externally managed, you can use brew install pip3 to install python packages system-wide._

```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
```
 
_The failing step (flutter - Flutter Pub Get) is a 3rd party step, please report the issue for the step’s repository here: https://github.com/DroidsOnRoids/bitrise-step-flutter/issues (Step resources/ Issue tracker on the build log page).
 
Xcode 15.3 stacks have a new python version compared to older stacks such as Xcode 14.3 stacks (3.11.5 → 3.12.2). With the new python version, [the command the step uses](https://github.com/DroidsOnRoids/bitrise-step-flutter/blob/master/macos.go#L16) to install the six phyton lib fails.
 
Based on this, similar GH issue: https://github.com/pypa/virtualenv/issues/988, the executed command should have a -H flag after sudo.
 
You could also try a Script step instead to run the flutter commands manually (flutter pub get and flutter precache --ios), in order to see if that works better._

I tried this steps - I added 3 script steps to the workflow

6. "Script" 
```
#!/bin/bash
brew install pipx
```

7. "Script"
```
#!/usr/bin/env bash
flutter pub get
```

8. "Script"
```
#!/usr/bin/env bash
flutter precache --ios
```

the 9. step is a the "Run build_runner" command - like that
`sudo -H packages pub run build_runner build --delete-conflicting-outputs`

and here i get always the same error - hope you guys can help me - thanks

**Comment by koral--** [comment]
Does the problem persist if you install `six` using `brew install six` inside the script or using the brew-install step https://bitrise.io/integrations/steps/brew-install before the flutter step?

**Comment by paulunder** [comment]
hi @koral-- thanks for your answer, no I tried already - I get the same error

**Comment by koral--** [comment]
Fixed in 0.1.5 https://github.com/bitrise-io/bitrise-steplib/pull/4202

**Comment by paulunder** [comment]
hi @koral-- thread is not solved...

**Comment by koral--** [comment]
You can either use version 0.1.5 using the git step source or wait until Bitrise staff merges the linked PR.
