### ISSUE TITLE
Step broken with Flutter 3.24.3

### ISSUE THREAD

**Issue by jwyrembelski** [DroidsOnRoids/bitrise-step-flutter#33]
Step fails immediately with following message: 

```
Config:
- version: 3.24.3
- working_dir: /Users/vagrant/git
- commands: [build macos]
Could not setup Android SDK, error: open /usr/local/share/android-sdk/tools/source.properties: no such file or directory
```

**Comment by p-nattapong** [comment]
Me too

**Comment by eg-t-hayasaka** [comment]
Hi everyone.

This is happening to me too.

I tried outputting a list of the $ANDROID_HOME directory on Bitrise, and there was no `tools` directory.

```bash
+ echo 'list ANDROID_HOME items.'
list ANDROID_HOME items.
+ ls -la /usr/local/share/android-sdk
total 8
drwxr-xr-x  12 vagrant  staff  384 Sep 13 10:56 .
drwxr-xr-x   3 root     wheel   96 Sep 13 10:54 ..
-rwxr-xr-x   1 vagrant  staff   16 Oct 15 10:09 .knownPackages
drwxr-xr-x   2 vagrant  staff   64 Sep 13 10:56 .temp
drwxr-xr-x   3 vagrant  staff   96 Sep 13 10:55 build-tools
drwxr-xr-x   4 vagrant  staff  128 Sep 13 10:55 cmake
drwxr-xr-x   4 vagrant  staff  128 Sep 17 07:37 cmdline-tools
drwxr-xr-x  29 vagrant  staff  928 Sep 13 10:56 emulator
drwxr-xr-x   8 vagrant  staff  256 Sep 13 10:55 licenses
drwxr-xr-x   3 vagrant  staff   96 Sep 13 10:55 ndk
drwxr-xr-x  15 vagrant  staff  480 Sep 13 10:56 platform-tools
drwxr-xr-x   5 vagrant  staff  160 Sep 13 10:56 platforms
```

I don't know why the tools directory is missing.

I was using Flutter version 3.19.5 when I encountered this error.

**Comment by eg-t-hayasaka** [comment]
hi everyone.

When I contacted Bitrise, they told me that in the Xcode16 stack, "source.properties has been moved to another location."

It seems that a temporary workaround is to create a symbolic link as follows:

```
ln -s /usr/local/share/android-sdk/build-tools/35.0.0 /usr/local/share/android-sdk/tools
```

**Comment by koral--** [comment]
I've just updated the way of finding the build-tools version.
Now, instead of parsing the `$ANDROID_HOME/tools/source.properties` it looks for the newest version in `$ANDROID_HOME/build-tools`. Even if such dir does not exist the tools are assumed to be out of date instead of failing fast.

**Comment by eg-t-hayasaka** [comment]
thank you @koral-- for the correction ! ❤️
