### ISSUE TITLE
lint-gradle-api-26.1.2.jar not found

### ISSUE THREAD

**Issue by Carmelo992** [DroidsOnRoids/bitrise-step-flutter#9]
Hi,
Since few days ago, the package "lint-gradle-api-26.1.2.jar" there isn't anymore on jcenter and the build with your step started to fail.

The same problem happens also locally but I solved this issue according with this link:
https://stackoverflow.com/a/52946279

It suggests to update the 'com.android.tools.build:gradle' from 3.1.2 to 3.2.1

When are you planning to release a new version to fix the problem on your step?

Thanks in advance,
Carmelo

**Comment by koral--** [comment]
OK, it seems that they merged a PR with fix but it is not yet released. I'll add ability to specify git branch or tag as a version in step input. So you can specify e.g. `master` and use that patch.

**Comment by koral--** [comment]
Added in version 0.0.7
